"""Initial Migration

Revision ID: 16d99137c1fc
Revises: 
Create Date: 2024-07-27 13:34:45.217673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d99137c1fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_street_vendor', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('street_vendors',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('street_vendor_name', sa.String(), nullable=True),
    sa.Column('stree_vendor_category', sa.Enum('makanan_dan_minuman', 'pakaian_dan_aksesoris', 'buah_dan_sayuran', 'barang_bekas_dan_barang_antik', 'mainan_anak_anak', 'jasa', 'kerajinan_tangan', 'produk_kesehatan_dan_kecantikan', 'peralatan_rumah_tangga', 'barang_elektronik', name='street_vendor_category_enum'), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('street_vendors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
