"""Item model

Revision ID: 2be1a4e3ea25
Revises: 6a13e3e4b67a
Create Date: 2024-07-27 19:02:38.110735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be1a4e3ea25'
down_revision: Union[str, None] = '6a13e3e4b67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('street_vendors_email_key', 'street_vendors', type_='unique')
    op.drop_column('street_vendors', 'email')
    op.drop_column('street_vendors', 'password')
    op.drop_column('street_vendors', 'name')
    op.drop_column('street_vendors', 'is_street_vendor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('street_vendors', sa.Column('is_street_vendor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('street_vendors', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('street_vendors', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('street_vendors', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('street_vendors_email_key', 'street_vendors', ['email'])
    # ### end Alembic commands ###
