"""Street Vendor

Revision ID: 6a13e3e4b67a
Revises: 16d99137c1fc
Create Date: 2024-07-27 17:47:21.580155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a13e3e4b67a'
down_revision: Union[str, None] = '16d99137c1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('street_vendors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('street_vendors', sa.Column('name', sa.String(), nullable=True))
    op.add_column('street_vendors', sa.Column('password', sa.String(), nullable=True))
    op.add_column('street_vendors', sa.Column('is_street_vendor', sa.Boolean(), nullable=False))
    op.add_column('street_vendors', sa.Column('street_vendor_category', sa.Enum('makanan_dan_minuman', 'pakaian_dan_aksesoris', 'buah_dan_sayuran', 'barang_bekas_dan_barang_antik', 'mainan_anak_anak', 'jasa', 'kerajinan_tangan', 'produk_kesehatan_dan_kecantikan', 'peralatan_rumah_tangga', 'barang_elektronik', name='street_vendor_category_enum'), nullable=True))
    op.create_unique_constraint(None, 'street_vendors', ['email'])
    op.drop_column('street_vendors', 'stree_vendor_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('street_vendors', sa.Column('stree_vendor_category', postgresql.ENUM('makanan_dan_minuman', 'pakaian_dan_aksesoris', 'buah_dan_sayuran', 'barang_bekas_dan_barang_antik', 'mainan_anak_anak', 'jasa', 'kerajinan_tangan', 'produk_kesehatan_dan_kecantikan', 'peralatan_rumah_tangga', 'barang_elektronik', name='street_vendor_category_enum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'street_vendors', type_='unique')
    op.drop_column('street_vendors', 'street_vendor_category')
    op.drop_column('street_vendors', 'is_street_vendor')
    op.drop_column('street_vendors', 'password')
    op.drop_column('street_vendors', 'name')
    op.drop_column('street_vendors', 'email')
    # ### end Alembic commands ###
