"""Item change attribute name

Revision ID: ec348ad80490
Revises: c1b9edbd0ed4
Create Date: 2024-07-27 22:40:48.389770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec348ad80490'
down_revision: Union[str, None] = 'c1b9edbd0ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('street_vendor_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_street_vendor_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'street_vendors', ['street_vendor_id'], ['user'])
    op.drop_column('items', 'street_vendor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('street_vendor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_street_vendor_fkey', 'items', 'street_vendors', ['street_vendor'], ['user'])
    op.drop_column('items', 'street_vendor_id')
    # ### end Alembic commands ###
